# Configurações da API
IAHUB_API_KEY = "760c7b9bb897031e52324a669c56be164a38adf4017916d3d36192b41d594cbf"
IAHUB_URL = "https://api.iahub.site/chat"
STRIPE_PUBLIC_KEY = "pk_live_51Rpsqc7bgFjbGUmUDs1RDBJis2zJ8lBQk40wGmI3LboRV7Sqds21oe2gUZKL5CncqykxUpUDNTo3zUalZkL7DFvT00HRsKxcjC"
SUPABASE_URL = "https://adqhhwbeffhzicfteort.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcWhod2JlZmZoemljZnRlb3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODE2MjgsImV4cCI6MjA3MjI1NzYyOH0.oj5NBW9zN0JuR623RsC_DJza_5fZTFhR1A7i_O6tceo"