# Configurações da API
IAHUB_API_KEY = "760c7b9bb897031e52324a669c56be164a38adf4017916d3d36192b41d594cbf"
IAHUB_URL = "https://api.iahub.site/chat"
STRIPE_PUBLIC_KEY = "pk_live_51Rpsqc7bgFjbGUmUDs1RDBJis2zJ8lBQk40wGmI3LboRV7Sqds21oe2gUZKL5CncqykxUpUDNTo3zUalZkL7DFvT00HRsKxcjC"